/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.com.bizpol.wspolnota.ui;

import java.awt.Rectangle;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import pl.com.bizpol.wspolnota.core.Community;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreeModel;
import javax.swing.tree.TreePath;
import pl.com.bizpol.wspolnota.core.CommunityTenant;
import pl.com.bizpol.wspolnota.dao.CommunityDAO;
import pl.com.bizpol.wspolnota.dao.CommunityTenantDAO;
import pl.com.bizpol.wspolnota.dao.UserDAO;
import pl.com.bizpol.wspolnota.util.CommunityTreeModel;
import pl.com.bizpol.wspolnota.util.ComunityTreeRenderer;

/**
 *
 * @author Archii
 */
public final class PropertyPanel extends javax.swing.JPanel {

    /**
     * Creates new form PropertyPanel
     */
    List<Community> cList = new ArrayList<>();    
    DefaultTreeModel communityModel;
    MainWindow mainWindow;    
    CommunityIFrame communityIFrame;
    
    public PropertyPanel(java.awt.Frame parent) {     
        
        mainWindow = (MainWindow) parent;
        
        initComponents();
        
        //pobieram dane mysql do zmiennej cList
        getTreeMysqlData();
        
        communityModel = new CommunityTreeModel(cList);
        
        jTree1.setModel(communityModel);
                
        jTree1.setShowsRootHandles(true);
        // ustawianie icon tekstu dla drzewa        
        jTree1.setCellRenderer(new ComunityTreeRenderer());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        jToolBar1.setRollover(true);

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setDividerSize(3);
        jSplitPane1.setMinimumSize(new java.awt.Dimension(5, 25));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jDesktopPane1);

        jScrollPane1.setBorder(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(20, 322));

        jTree1.setModel(communityModel);
        jTree1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        jSplitPane1.setLeftComponent(jScrollPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
        // TODO add your handling code here:
        
        if (!jTree1.isSelectionEmpty()) {            
            TreePath path = (TreePath) jTree1.getSelectionPath();
            
            DefaultMutableTreeNode selected = (DefaultMutableTreeNode) path.getLastPathComponent();            
            
            if (selected.getLevel() > 1){
                System.out.println("Selected level " + selected.getLevel());
            } else if (!selected.isRoot()) {
                Community community = (Community) selected.getUserObject();
                
                community.setName("aaaaaaaaa");
                if (!community.getCommunityWindow()){
                    System.out.println(community.getId() +
                        ": " +
                        community.getName() + ", " + community.getStreet() +
                        " " + community.getStreetNo());
                    
                    Rectangle b = jDesktopPane1.getBounds();
                    communityIFrame = new CommunityIFrame(community, mainWindow);
                    jDesktopPane1.add(communityIFrame);
                    communityIFrame.setBounds(b);
                    communityIFrame.setLocation(0, 0);
                    communityIFrame.setVisible(true);
                    communityIFrame.requestFocusInWindow();
                    communityIFrame.repaint();                    
                }
                
                //załadowanie lokatorów z bazy danych jako lista w objekcie commiunity
                
                if (community.getTenants().isEmpty()) {
                    try {
                        // pobieram listę lokatorów
                        CommunityTenantDAO ctDAO = new CommunityTenantDAO();
                        List<CommunityTenant> communityTenants = ctDAO.getAllCommunityTenants(community.getId());
                        community.setTenants(communityTenants);
                        
                        //TreeModel model = jTree1.getModel();                        
                        
                        int i = 0;
                        
                        for (CommunityTenant commT : communityTenants) {
                            System.out.println(commT.toString());
                            selected.add(new DefaultMutableTreeNode(commT));
                            i++;
                        }
                        jTree1.expandPath(path);
                        jTree1.setExpandsSelectedPaths(true);
                        jTree1.setSelectionPath(path);
                        jTree1.repaint();
                        
                        
                        
                    } catch (Exception ex) {
                        Logger.getLogger(PropertyPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
                
                
                
//                if (path.getPathComponent(WIDTH)){
//                    
//                }
            }
            
            if(communityIFrame.isIcon()){
                try {
                    communityIFrame.setIcon(false);
                    communityIFrame.setSelected(true);
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(PropertyPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
            
       
        
        
        
        
    }//GEN-LAST:event_jTree1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
    
     public void getTreeMysqlData() {
        
        try {            
            CommunityDAO cDAO = new CommunityDAO();            
            cList = cDAO.getAllCommunities();  
            
        } catch (Exception ex) {
            Logger.getLogger(UserDAO.class.getName()).log(Level.SEVERE, "Błąd połączenia", ex);
        }
        
    }
}
